tio/tio

- src/include/gotty/options.h
- src/options.c
- src/tty.c
This patch adds an option to insert a small delay between transmitted bytes. This is useful when working with slow devices that cant process incoming bytes at full wire speed.
> Add option for setting inter-character delay

- configure.ac
- src/Makefile.am
Instead, use pkg-config to find out where the completions should go.
While packaging 1.4 for Debian, I stumbled across https://bugs.debian.org/776954 so this updates configure.ac and Makefile.am to be in line with the instructions from https://github.com/scop/bash-completion.
> Don't hardcode path for bash completions

- src/error.c
- src/log.c
- src/main.c
- src/options.c
- src/time.c
- src/tty.c
This makes use of 8d6d202 (Enable large file support) for real.
config.h has to be included before the standard headers as it defines _FILE_OFFSET_BITS.
> Include config.h before standard headers

- configure.ac
- src/Makefile.am
- src/bash-completion/tio.in
Note that I'm not a bash-completion user, so this is mostly untested.
> Generated bash completion at configure time

- ChangeLog
ChangeLog is primary useful for users who don't have the git repository at hand.
Replace git commit references with version numbers; or if the change only cleans up another change with no release in between, remove the changelog item completely.
> Removed git commit references from ChangeLog

- man/tio.1
- src/include/tio/tty.h
- src/tty.c
We need tcsendbreak(), it works akin to SysRq on Linux, with similar functionality on other OSes.
Actually, for me it resets the target immediately, but meh, that's good enough, S-U-B is obsolete nowadays and worse than just B on any modern filesystem.
> 'ctrl-t b' to send serial break.

- src/setspeed2.c
Musl's inclusion tree slightly differs from glibc, therefore TCGETS2 is
not reachable through sys/ioctl.h, so asm/ioctls.h needs to be included
too.
> Add missing header file under musl-libc

- src/log.c
Logfiles are important to see what happend, in particular if something
unexpected happened; so we want to make sure that the logfile is flushed
to disk.
Before this change, the logfile was typically written at the end in
a large chunk as the default (large) buffering applied. Now, characters are
written out ASAP, so it is possible to get a live-view with a
tail -f <logfile>
> Write to logfile as soon as we have the data, don't buffer.

- src/tty.c
This mostly is intended to have local echo output exactly what is sent
to the remote endpoint.
A nice side-effect is, that it also fixes tty-implementations, that can't
deal with the OCRNL flag on tio.c_oflag.
> Map CR->NL locally on output instead of using tio.c_oflag |= OCRNL.

- src/tty.c
At least on OS X (10.11), local echo only prints everything after a newline is sent, which is not very convenient. So force flush the stdout after every character is typed.
Tested on a mac only, don't have any Linux nearby.
> Flush every local echo-ed char

- man/tio.1
- src/include/tio/tty.h
- src/tty.c
Control DTR/RTS lines manually may be useful e.g. in case when communicating remotely with embedded device and RESET pin is connected to DTR / RTS
> add serial lines manual control

- src/tty.c
In order for local echo to work properly, we have to either call
fflush(stdout) after every character or just disable line buffering.
This change uses setbuf(stdout, NULL) to do the latter.
Closes #92
> Disable line buffering in stdout

- src/tty.c
In order for local echo to work properly, we have to either call
fflush(stdout) after every character or just disable line buffering.
This change calls fflush() after putchar().
Closes #92
> fflush() after putchar() for print_hex and print_normal

- configure.ac
String comparison with == is not POSIX compliant and can fail with e.g.
dash.
Fixes https://github.com/tio/tio/issues/115
> Make comparison POSIX compliant

- src/tty.c
I have not tested this, but it looks like a bug.
> Exit if output speed cannot be set.

- src/setspeed2.c
Include ioctls.h and termbits.h from asm-generic instead of asm to avoid
the following build failure:
```
In file included from setspeed2.c:24:0:
/home/naourr/work/instance-0/output-1/host/sparc64-buildroot-linux-gnu/sysroot/usr/include/asm/termbits.h:17:8: error: redefinition of 'struct termio'
struct termio {
^~~~~~
In file included from /home/naourr/work/instance-0/output-1/host/sparc64-buildroot-linux-gnu/sysroot/usr/include/sys/ioctl.h:29:0,
from setspeed2.c:22:
/home/naourr/work/instance-0/output-1/host/sparc64-buildroot-linux-gnu/sysroot/usr/include/bits/ioctl-types.h:36:8: note: originally defined here
struct termio
^~~~~~
```
Fixes:
- http://autobuild.buildroot.org/results/1a7418b9cd11374a250f7509d5bddcc864375e1c
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> src/setspeed2.c: fix redefinition of termio

- src/Makefile.am
Out of tree builds are currently broken because $(top_srcdir)src/include
is not in the search path. In tree builds are working because autconf add
$(top_builddir)/src/include to the search path for the generated config.h.
As $(top_builddir) and $(top_srcdir) are identical during in tree builds
the search path still end up beeing somehow correct.
To fix this add -I$(srcdir)/include to the CPPFLAGS in Makefile.am.
> Fix out of tree builds

- src/tty.c
This fixes the complaint in #81 by printing the reason why a tty hasn't been successfully connected yet.
Example when a device is plugged in and out while tio is running:
```
[15:25:49] tio v1.32
[15:25:49] Press ctrl-t q to quit
[15:25:49] /dev/ttyUSB1: No such file or directory. Waiting...
[15:26:00] Connected
[15:26:02] Disconnected
[15:26:03] /dev/ttyUSB1: No such file or directory. Waiting...
```
Example when user doesn't have permission to open tty:
```
[15:17:00] tio v1.32
[15:17:00] Press ctrl-t q to quit
[15:17:00] /dev/ttyUSB0: Permission denied. Waiting...
```
> Show error when failing to open a tty

- src/tty.c
If stdout is buffered with `putchar()`, local echo will not print anything until the next return. Make sure output is flushed so that each typed character shows up immediately.
(This used to work, not sure when it broke)
> Local echo: show character by character even if stdout buffered.

- src/bash-completion/tio.in
Add completion of `-t` and `--timestamp` to bash completion script.
> Add -t/--timestamp to bash completion script.

- src/bash-completion/tio.in
Add bash completion of tty devices from /dev/tty* and /dev/serial/by-id/* if it exists.
> Add bash completion of tty devices

- src/tty.c
This is to fix the issue #104. The timestamp will always be
printed at the beginning of line:
[10:25:56] Switched to hexadecimal mode
0d 0a 0d [10:25:57] 41 43 52 4e 3a 5c 3e 0d 0a 0d [10:25:58] 41
is changed to:
[12:34:56] 45 72 72 6f 72 3a 20 49 6e 76 61 6c 69 64 20
[12:34:56] 41 43 52 4e 3a 5c 3e
[12:34:56] 41 43 52 4e 3a 5c 3e
[12:34:57] 41 43 52 4e 3a 5c 3e 6c 73
> Output newline on stdout with hex print mode

- src/tty.c
Flag ONLCRNL expects code \n after press Enter, but on some systems \r is send instead.
> Newline: handle booth NL and CR

- meson.build
Hi Martin,
Can you double-check on your side that this does not break build ?
It works for me on macOS and Debian 10.10.
BR,
Sly
> Fix TCGETS2 search on Darwin.

- configure.ac
- src/Makefile.am
- src/iossiospeed.c
- src/tty.c
It's me again to cause more trouble!
I figured out how to support high speeds (1Mbps, 2Mbps, ...) on OS X by peeking at how pyserial does it, and it seems relatively straightforward. This works at least on my macbook running Mojave.
> add support for high bps on OS X

- man/tio.1.in
- meson_options.txt
- src/conffile.c
- src/conffile.h
- src/main.c
- src/meson.build
- src/misc.h
- src/options.c
- src/options.h
Hi, 
I noticed #107 and thought it was definitely something I could use.
Here is an attempt at reading configuration options from a config file.
This isn't complete but I was curious to know what people think of it.
basically when calling `tio my_device`, tio looks for a section called `my_device` for options.
If it exists, that section is used otherwise we try to fallback on `default`.
Thanks,
Liam
> Add support for a configuration file

- man/tio.1.in
- src/bash-completion/tio.in
- src/configfile.c
- src/main.c
- src/meson.build
- src/options.c
- src/options.h
- src/socket.c
- src/socket.h
- src/tty.c
This feature allows an external program to inject output into and
listen to input from a serial port via a Unix domain socket (path
specified via the -S/--socket command line flag, or the socket
config file option) while tio is running. This is useful for ad-hoc
scripting of serial port interactions while still permitting manual
control. Since many serial devices (at least on Linux) get confused
when opened by multiple processes, and most commands do not know
how to correctly open a serial device, this allows a more convenient
usage model than directly writing to the device node from an external
program.
Any input from clients connected to the socket is sent on the serial
port as if entered at the terminal where tio is running (except that
ctrl-t sequences are not recognized), and any …
> Add support for external control via a Unix domain socket.

- src/include/tio/log.h
- src/include/tio/options.h
- src/log.c
- src/options.c
- src/tty.c
The log without escape key stripped is like:
^M[12:47:17] ACRN:\>
^M[12:47:17] ACRN:\>lasdfjklsdjf
^M
^M[12:47:18] Error: Invalid command.
^M[12:47:19] ACRN:\>
^M[12:47:26] ACRN:\>
^M[12:47:26] ACRN:\>sdafkljsdkaljfklsadjflksdjafjsda^H ^H^H...
^M
^M[12:47:31] Error: Invalid command.
After strip escape key, the log is like:
[12:49:18] ACRN:\>
[12:49:19] ACRN:\>
[12:49:19] ACRN:\>ls
[12:49:19] Error: Invalid command.
[12:49:19] ACRN:\>
[12:49:19] ACRN:\>dfaslhj
[12:49:24] Error: Invalid command.
Beside escape key, it also handle backspace key as well.
> Allow strip escape sequence characters from log file

- src/configfile.c
If the malloc function failed to allocate memory, it is unlikely that the program will continue to function properly the null pointer returned will leads almost always to fatal error in the program .
> handle malloc failure

- README.md
- man/tio.1.in
- src/bash-completion/tio.in
- src/configfile.c
- src/options.c
- src/options.h
- src/tty.c
- src/tty.h
MCUs like the ESP32 can be reset if the serial port DTR line is
pulsed for a short time.  You could just type CTRL-T d CTRL-T d
but that's a little awkward since you have to lift your finger
off the CTRL key to type the ds.  Now you can just type CTRL-T D.
* Added new command "D" to pulse the DTR line.  I.E.  Toggle its
state twice with a configurable duration between toggles.
* Added new config/command line option "--dtr-pulse-duration" to set
the duration between the DTR state toggles.  The default is
100ms.
Resolves #153
> Add Pulse DTR command

- README.md
MacPorts support is added by https://github.com/macports/macports-ports/pull/15400
It's not merged yet, but I created this PR to indicate that there's a pending PR for it and to update the readme
Thanks for your work.
> Add MacPorts install instructions

- src/signals.c
If the remote end of a socket is closed between when an input character
is received from the serial port and when it is written to the socket,
tio will receive a SIGPIPE signal when writing the character to the
socket, which will terminate the program. To prevent this, ignore the
signal, which will cause write(2) to return -EPIPE, causing tio to close
the socket.
> Ignore SIGPIPE signals

- src/socket.c
- src/socket.h
- src/tty.c
- src/tty.h
I noticed NL characters were getting mapped to CR when I was using serial mode. For my use case, I need mapping disabled.
I saw this in the [TODOs](https://github.com/tio/tio/blob/master/TODO): "Mapping flags INLCR, IGNCR, ICRNL needs implementation for socket mode". This is my attempt at that task. I based the implementation on these [docs](https://pubs.opengroup.org/onlinepubs/9699919799.2016edition/basedefs/V1_chap11.html#tag_11).
Couple things to callout:
1. Although the mapping flags seems to be the most intuitive, this is a breaking change for anyone relying on the existing default socket behavior.
2. Option parsing logic is duplicated. One alternative is passing in the mapping flags from tty.c. But I'm not a C developer, so I just went with the simplest approach.
I'm open to …
> Support input mapping modes for sockets

- src/tty.c
If `tio` is launched with Windows Terminal, following error will spam when resizing terminal window:
```
[22:31:21.594] tio v2.6
[22:31:21.597] Press ctrl-t q to quit
[22:31:21.608] Warning: Could not open tty device (No such file or directory)
[22:31:21.608] Waiting for tty device..
[22:31:23.621] Warning: Could not read from stdin (Interrupted system call)
[22:31:23.621] Warning: Could not write to pipe (Bad address)
[22:31:23.635] Warning: Could not read from stdin (Interrupted system call)
[22:31:23.635] Warning: Could not write to pipe (Bad address)
[22:31:23.663] Warning: Could not read from stdin (Interrupted system call)
[22:31:23.663] Warning: Could not write to pipe (Bad address)
[22:31:23.677] Warning: Could not read from stdin (Interrupted system call)
[22:31:23.677] Warning: …
```
> Ignore EINTR error.

- README.md
- man/tio.1.in
- src/meson.build
- src/misc.h
- src/tty.c
- src/xymodem.c
This is a draft pull request: I'm happy with the algorithm, still thinking about code clarity and coding standards.
Notes for tty.c:
- I seem to have accidentally reverted the last update on tty.c; will be corrected in the final pull request
- line 762: how do I use tio_printf without having a '\n' added?
Notes for xymodem.c:
- Probably I should use tio_warning_printf for line I/O errors?
- Does it make sense to report all these errors separately? The lrzsz suite just aborts the transfer on line errors.
- Maybe the loops around line reads need to be factored out into a separate routine -- not sure this improves readability.
- Does using a struct for the xmodem packet make sense? It does make clearer what the code does, but it makes adding support for both 128 byte and 1024 byte payloads …
> Add xmodem and ymodem file send support

- man/tio.1.in
.eo/.ec sections seemingly need explicit empty lines using .sp
Otherwise, troff complains:
```
troff:<standard input>:535: warning: expected numeric expression, got '\'
troff:<standard input>:538: warning: expected numeric expression, got '\'
troff:<standard input>:541: warning: expected numeric expression, got '\'
```
> Fix troff warning

- man/tio.1.in
- man/tio.1.txt
- src/bash-completion/tio.in
- src/tty.c
Added map of form feed to ESC-c on input for terminals that do not clear screen on ^L but do on ESC-c.
> Add map FF to ESC-c on input

- src/options.c
- src/rs485.c
Failing to check that a call to 'sscanf' actually writes to an output variable can lead to unexpected behavior at reading time.
> Check return values of sscanf()

- man/tio.1.in
- man/tio.1.txt
- src/tty.c
- src/xymodem.c
Clarify old Xmodem option as `Xmodem-1K`, new `Xmodem-CRC` can be selected by `ctrl+t X`.
Tested on Silabs Gecko bootloader.
> Add Xmodem-CRC support.

- examples/lua/automatic-login.lua
As mentioned in the discussion in https://github.com/tio/tio/pull/240, the example can be improved with the ability to return the matched text from `expect`. This updates that example to use the new functionality.
> Update auto-login example with new expect logic

- src/tty.c
- src/xymodem.c
- src/xymodem.h
I added a function that will receive xmodem files
There are now two CRC calculating functions, one that does byte by byte (which I implemented) and one that does the whole packet at once (already exists).  I just added the byte by byte one as I think it can be more versatile.
I modified tty.c such that the help printout and the subcommand for xmodem now suggests and lists an option for receiving files via XMODEM-CRC.  I didn't implement XMODEM-1K, but it should be simple to implement later.
For writing the received file to disk, I used the same prompt as the send option to get a filename, then use the `open(filename, O_WRONLY | O_CREAT | O_TRUNC);` command to make a new file on disk to write bytes to as they are read from the serial buffer.
> Adding XMODEM receive support

- README.md
- man/tio.1.in
- src/script.c
- src/script.h
- src/tty.c
With this changes, `ctrl-t r` prompt for script file name, and `ctrl-t R` for shell command to execute. On empty input, `ctrl-t r` runs the default script provided in options or in configuration file. This makes workflow close to TeraTerm where you can choose and run arbitrary macro files during interactive session.
By the way, what about replacing `tio_readln` with GNU readline, which adds auto-completion for file names, history, etc.?
> Prompt for Lua script or shell command in interactive session

- src/script.c
- src/tty.c
Closes: #268
Call tio_printf() after completing xymodem_send().
> Print correct 'Done' timestamp for X- and Y-modem transfers

- src/configfile.c
Not much more to say. I tested it locally.
> The log-directory options is not read from the configuration file.

- src/main.c
- src/tty.c
This makes it possible to pipe output to other programs cleanly.
> Disable stdout buffering globally

- src/script.c
They prevent regexec() from seeing the remainder of the buffer.
> Don't add null characters to the expect buffer

- man/tio.1.in
- man/tio.1.txt
- src/bash-completion/tio.in
- src/options.c
- src/options.h
- src/tty.c
This pull request introduces a new input mapping flag, ICRCRNL, which translates carriage return (CR) characters to carriage return + newline (CRNL). This mapping is designed to serve as a simpler alternative to using the combination of INLCRNL and ICRNL.
The existing combination of INLCRNL and ICRNL also alters the actual content written to the log file, making it impossible to reconstruct the original input. The new ICRCRNL flag avoids this issue.
> Add new mapping ICRCRNL to map CR to CRNL

- src/tty.c
Git is being dumb about
https://github.com/tio/tio/commit/67c071633dc6d659fae1e529a85f5990531e1669 This PR is identical to that one and will supercede it.
Fix --auto new and --auto latest on MacOS.
'device_list' was both a global (eww!) and a local inside tty_search_for_serial_devices(). The local got set and returned, so it looked sane, but the caller used the global instead of the return value of the function it had just called, meaning (global) device_list was NULL while (ignored, local) device_list held a perfectly lovely linked list.
Tested:
tio --auto new waits for a new device to appare and connects tio --latest will connect to the most recently attached device
which, in most worlds, is the most recently enumerated USB
device, conveniently skipping all the bluetooth nonsense.
If …
> Fix --auto new and --auto latest on MacOS. (redo)

- src/script.c
This PR fixes the problem of the Lua script stopping output if it has an output that includes a null termination. For example, the following Lua script:
```lua
write("\x01\x02\x03\x04\x00\x05\x06\x07\x08")
```
outputs only the following bytes (hex mode) in the current head of master f887756a7159967e015e3422e9ab04a82db8945f
```shell
01 02 03 04
```
> fix: lua script stops output if it includes null termination

- src/script.c
In Lua, strings may contain null characters, this means when working with the Lua C API you must always use `lua_pushlstring` instead of `lua_pushstring` if there is no guarantee that the string contains no null bytes. Treating Lua strings as if they were C strings can result in them being truncated.
> Fix string truncation bug in scripting api
